### PR TITLE
Update setup.py as an mbuild plugin/recipe

### PR DESCRIPTION
**Pull request by mattwthompson**
Depends on https://github.com/mosdef-hub/mbuild/pull/501

### CODE REVIEW

**Comment by rmatsum836** [comment]
Is this good to merge?  It seems like this doesn't depend on whether the naming convention is `my_recipes` or `recipes`.

**Comment by mattwthompson** [comment]
Should be ok to merge, but we'll probably update it at some point.

@justinGilmer how to we plan to test that this is setup right (from the perspective of this package)? Should we add a unit test that just tries to import this from mbuild and doesn't error out?

**Comment by rmatsum836** [comment]
I think that's probably the best first test to have.  We can add more later.

**Comment by mattwthompson** [comment]
Might take some tweaking, depending on how we handle the internal `mb.recipes` imports there

**Comment by rmatsum836** [comment]
Thanks, LGTM

**Comment by rmatsum836** [comment]
And yeah we can merge this PR for now and tweak accordingly.

**Comment by mattwthompson** [comment]
That'll kill travis for a few days but should be good otherwise

**Comment by mattwthompson** [comment]
Hmm, well it worked on my local machine but not at all on Travis.

**Comment by rmatsum836** [comment]
I merged the master branch changes into this PR and Travis is passing now.  I'm going to go ahead and merge.

**Pull request merged**
