### PR TITLE
Rework solvated pore example into an aqueous electrolyte

### PR DESCRIPTION
**Pull request by mattwthompson**
#6 and a good candidate for #5

### CODE REVIEW

**Comment by mattwthompson** [comment]
The mac build is still failing for some travis issue. @rmatsum836 you are welcome to pull this branch and check it out before merging.

**Comment by rmatsum836** [comment]
Going to take a look at this now

**Comment by rmatsum836** [comment]
the `.yml` file is building with Python 3.5 for Linux and Python 3.4 for OSX.  This could be why Linux passes and OSX doesn't.

**Comment by mattwthompson** [comment]
That has to have been one of my worst misspellings ...

**Comment by mattwthompson** [comment]
Stalled and closing - feel free to re-open/takeover if this feature is of interest

**Pull request closed without merging**
